# Imagem Docker
image:
  file: .gitpod.Dockerfile

# Portas e Ações
ports:
  - name: localhost
    port: 4200
    onOpen: open-browser
    visibility: public

# Tarefas na Inicialização
tasks:
  - name: Start front-end
    before: export NG_CLI_ANALYTICS=ci
    init: echo n | npm i -g @angular/cli@17
    command: npm ci && npm run start
